const citiesToTimeZoneMap = {
    "Asia/Kashgar": "(GMT+6:00) Almaty, Novosibirsk",
    "Asia/Jerusalem": "(GMT+3:00) Jerusalem",
    "America/Phoenix": "(GMT-7:00) Arizona",
    "Europe/Berlin": "(GMT-2:00) Greenland",
    "Africa/Gaborone": "(GMT+2:00) Harare, Pretoria",
    "Asia/Seoul": "(GMT+9:00) Seoul",
    "Africa/Dar_es_Salaam": "(GMT+3:00) Nairobi",
    "America/Port-au-Prince": "(GMT-4:00) Caracas, La Paz",
    "America/Montreal": "(GMT-4:00) Eastern Time",
    "America/Panama": "(GMT-5:00) Bogota, Lima, Quito",
    "Asia/Ho_Chi_Minh": "(GMT+7:00) Bangkok, Hanoi, Jakarta",
    "America/Boise": "(GMT-6:00) Mountain Time",
    "Asia/Baghdad": "(GMT+3:00) Baghdad",
    "Africa/El_Aaiun": "(GMT+1:00) Lisbon",
    "Europe/Zagreb": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
    "America/Merida": "(GMT-5:00) Bogota, Lima, Quito",
    "Africa/Nouakchott": "(GMT+0:00) Casablanca, Monrovia",
    "America/Santiago": "(GMT-4:00) Caracas, La Paz",
    "Africa/Bissau": "(GMT+0:00) Casablanca, Monrovia",
    "America/Los_Angeles": "(GMT-7:00) Pacific Time",
    "America/Sitka": "(GMT-8:00) Alaska",
    "Asia/Jakarta": "(GMT+7:00) Bangkok, Hanoi, Jakarta",
    "Asia/Harbin": "(GMT+8:00) Beijing, Chongqing, Hong Kong SAR, Urumqi",
    "America/Belize": "(GMT-6:00) Central America",
    "America/Vancouver": "(GMT-7:00) Pacific Time",
    "Asia/Tbilisi": "(GMT+4:00) Abu Dhabi, Muscat",
    "Asia/Yerevan": "(GMT+4:00) Abu Dhabi, Muscat",
    "Europe/Tallinn": "(GMT+3:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
    "Asia/Magadan": "(GMT+11:00) Magadan, Solomon Islands, New Caledonia",
    "Australia/Perth": "(GMT+8:00) Perth",
    "America/North_Dakota": "(GMT-6:00) Central America",
    "Europe/Vilnius": "(GMT+3:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
    "Asia/Baku": "(GMT+4:00) Abu Dhabi, Muscat",
    "Asia/Tehran": "(GMT+4:30) Kabul",
    "Europe/Lisbon": "(GMT+1:00) Lisbon",
    "America/Araguaina": "(GMT-3:00) Brasilia",
    "America/Coral_Harbour": "(GMT-5:00) Central Time",
    "Asia/Novokuznetsk": "(GMT+7:00) Krasnoyarsk",
    "Asia/Thimphu": "(GMT+6:00) Astana, Dhaka",
    "Australia/Darwin": "(GMT+9:30) Darwin",
    "Africa/Freetown": "(GMT+0:00) Casablanca, Monrovia",
    "Atlantic/South_Georgia": "(GMT-2:00) Greenland",
    "Africa/Accra": "(GMT+0:00) Casablanca, Monrovia",
    "Asia/Sakhalin": "(GMT+11:00) Magadan, Solomon Islands, New Caledonia",
    "Australia/Adelaide": "(GMT+9:30) Adelaide",
    "America/Jamaica": "(GMT-5:00) Bogota, Lima, Quito",
    "Europe/Tirane": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
    "Asia/Vladivostok": "(GMT+10:00) Vladivostok",
    "America/Scoresbysund": "(GMT+0:00) Azores",
    "America/Moncton": "(GMT-3:00) Santiago",
    "Africa/Bujumbura": "(GMT+2:00) Harare, Pretoria",
    "America/Glace_Bay": "(GMT-3:00) Santiago",
    "Atlantic/Stanley": "(GMT-3:00) Santiago",
    "Africa/Porto-Novo": "(GMT-1:00) Cape Verde Islands",
    "America/Indiana": "(GMT-4:00) Caracas, La Paz",
    "Asia/Ashgabat": "(GMT+5:00) Baku, Tbilisi, Yerevan",
    "America/Detroit": "(GMT-4:00) Eastern Time",
    "America/Menominee": "(GMT-5:00) Central Time",
    "Asia/Novosibirsk": "(GMT+7:00) Krasnoyarsk",
    "Africa/Lagos": "(GMT-1:00) Cape Verde Islands",
    "America/Godthab": "(GMT-2:00) Greenland",
    "America/Yakutat": "(GMT-8:00) Alaska",
    "Europe/Volgograd": "(GMT+4:00) Abu Dhabi, Muscat",
    "Asia/Rangoon": "(GMT+6:30) Yangon Rangoon",
    "Asia/Qatar": "(GMT+3:00) Kuwait, Riyadh",
    "Indian/Antananarivo": "(GMT+3:00) Nairobi",
    "Asia/Khandyga": "(GMT+9:00) Seoul",
    "Arctic/Longyearbyen": "(GMT-2:00) Greenland",
    "Australia/Hobart": "(GMT+10:00) Hobart",
    "Pacific/Galapagos": "(GMT-6:00) Central America",
    "Asia/Oral": "(GMT+5:00) Ekaterinburg",
    "Asia/Taipei": "(GMT+8:00) Taipei",
    "Australia/Broken_Hill": "(GMT+9:30) Adelaide",
    "America/Dawson_Creek": "(GMT-7:00) Pacific Time",
    "Africa/Mbabane": "(GMT+2:00) Harare, Pretoria",
    "Africa/Cairo": "(GMT+2:00) Cairo",
    "America/Cambridge_Bay": "(GMT-6:00) Saskatchewan",
    "Asia/Aqtau": "(GMT+5:00) Ekaterinburg",
    "Asia/Hovd": "(GMT+7:00) Bangkok, Hanoi, Jakarta",
    "Asia/Ulaanbaatar": "(GMT+8:00) Irkutsk, Ulaanbaatar",
    "Africa/Nairobi": "(GMT+3:00) Nairobi",
    "America/Kentucky": "(GMT-4:00) Eastern Time",
    "Australia/Melbourne": "(GMT+10:00) Hobart",
    "America/Halifax": "(GMT-3:00) Santiago",
    "America/Ojinaga": "(GMT-6:00) Chihuahua, La Paz, Mazatlan",
    "America/Nome": "(GMT-8:00) Alaska",
    "Asia/Jayapura": "(GMT+9:00) Seoul",
    "Asia/Ust-Nera": "(GMT+10:00) Yakutsk",
    "Asia/Yakutsk": "(GMT+10:00) Yakutsk",
    "Asia/Irkutsk": "(GMT+8:00) Irkutsk, Ulaanbaatar",
    "America/Tegucigalpa": "(GMT-6:00) Central America",
    "Europe/Zaporozhye": "(GMT+3:00) Istanbul, Moscow, St. Petersburg, Volgograd",
    "America/Fortaleza": "(GMT-3:00) Brasilia",
    "America/Yellowknife": "(GMT-6:00) Saskatchewan",
    "Pacific/Fiji": "(GMT+12:00) Fiji Islands",
    "Europe/Bratislava": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
    "America/Iqaluit": "(GMT-4:00) Eastern Time",
    "America/Resolute": "(GMT-5:00) Central Time",
    "Africa/Brazzaville": "(GMT+1:00) West Central Africa",
    "Africa/Libreville": "(GMT-1:00) Cape Verde Islands",
    "America/New_York": "(GMT-4:00) Eastern Time",
    "Asia/Samarkand": "(GMT+5:00) Islamabad, Karachi, Tashkent",
    "Africa/Johannesburg": "(GMT+2:00) Harare, Pretoria",
    "America/Bahia": "(GMT-3:00) Brasilia",
    "Europe/Zurich": "(GMT+2:00) Brussels, Copenhagen, Madrid, Paris",
    "America/Paramaribo": "(GMT-3:00) Brasilia",
    "Europe/Samara": "(GMT+4:00) Abu Dhabi, Muscat",
    "Asia/Pyongyang": "(GMT+9:00) Seoul",
    "Europe/Ljubljana": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
    "Pacific/Port_Moresby": "(GMT+10:00) Brisbane",
    "America/Manaus": "(GMT-4:00) Caracas, La Paz",
    "Africa/Kampala": "(GMT+3:00) Nairobi",
    "America/Rio_Branco": "(GMT-5:00) Bogota, Lima, Quito",
    "Africa/Bamako": "(GMT+0:00) Casablanca, Monrovia",
    "America/Argentina": "(GMT-3:00) Buenos Aires, Georgetown",
    "Asia/Yekaterinburg": "(GMT+5:00) Ekaterinburg",
    "America/Goose_Bay": "(GMT-3:00) Brasilia",
    "Africa/Conakry": "(GMT+0:00) Casablanca, Monrovia",
    "Africa/Asmara": "(GMT+3:00) Kuwait, Riyadh",
    "America/Chihuahua": "(GMT-6:00) Chihuahua, La Paz, Mazatlan",
    "Europe/Warsaw":
        "(GMT+2:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    "Asia/Karachi": "(GMT+5:00) Islamabad, Karachi, Tashkent",
    "Europe/Istanbul": "(GMT+3:00) Bucharest",
    "Africa/Bangui": "(GMT+1:00) West Central Africa",
    "America/Lima": "(GMT-5:00) Bogota, Lima, Quito",
    "Asia/Aden": "(GMT+3:00) Nairobi",
    "America/Port_of_Spain": "(GMT-4:00) Caracas, La Paz",
    "America/Tijuana": "(GMT-7:00) Tijuana",
    "Asia/Nicosia": "(GMT+3:00) Jerusalem",
    "Europe/Simferopol": "(GMT+3:00) Bucharest",
    "Europe/Budapest":
        "(GMT+2:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    "America/Santo_Domingo": "(GMT-4:00) Caracas, La Paz",
    "Europe/Kaliningrad":
        "(GMT+2:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    "Europe/London": "(GMT+1:00) Edinburgh, London",
    "Pacific/Guadalcanal": "(GMT-11:00) Midway Island, Samoa",
    "Asia/Shanghai": "(GMT+8:00) Beijing, Chongqing, Hong Kong SAR, Urumqi",
    "Africa/Windhoek": "(GMT-1:00) Cape Verde Islands",
    "Asia/Dhaka": "(GMT+6:00) Astana, Dhaka",
    "Europe/Mariehamn":
        "(GMT+3:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
    "America/La_Paz": "(GMT-4:00) Caracas, La Paz",
    "America/Recife": "(GMT-3:00) Brasilia",
    "Europe/Athens": "(GMT+3:00) Athens, Minsk",
    "America/Mexico_City": "(GMT-5:00) Guadalajara, Mexico City, Monterrey",
    "America/Chicago": "(GMT-5:00) Central Time",
    "Asia/Amman": "(GMT+3:00) Jerusalem",
    "Atlantic/Reykjavik": "(GMT+0:00) Azores",
    "Africa/Mogadishu": "(GMT+3:00) Nairobi",
    "Africa/Malabo": "(GMT+1:00) West Central Africa",
    "Africa/Ndjamena": "(GMT+1:00) West Central Africa",
    "Asia/Choibalsan": "(GMT+8:00) Irkutsk, Ulaanbaatar",
    "Asia/Riyadh": "(GMT+3:00) Kuwait, Riyadh",
    "Africa/Blantyre":
        "(GMT+2:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    "Australia/Sydney": "(GMT+10:00) Canberra, Melbourne, Sydney",
    "Asia/Dushanbe": "(GMT+5:00) Islamabad, Karachi, Tashkent",
    "Europe/Belgrade":
        "(GMT+2:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    "Europe/Luxembourg": "(GMT+2:00) Brussels, Copenhagen, Madrid, Paris",
    "Europe/Podgorica": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
    "Asia/Brunei": "(GMT+8:00) Kuala Lumpur, Singapore",
    "America/Asuncion": "(GMT-4:00) Caracas, La Paz",
    "Europe/Prague": "(GMT-2:00) Greenland",
    "America/Atikokan": "(GMT-5:00) Central Time",
    "America/Pangnirtung": "(GMT-4:00) Eastern Time",
    "Africa/Dakar": "(GMT+0:00) Casablanca, Monrovia",
    "America/Edmonton": "(GMT-6:00) Central America",
    "Asia/Kuwait": "(GMT+3:00) Kuwait, Riyadh",
    "Asia/Bishkek": "(GMT+6:00) Almaty, Novosibirsk",
    "Europe/Moscow": "(GMT+3:00) Istanbul, Moscow, St. Petersburg, Volgograd",
    "Australia/Brisbane": "(GMT+10:00) Brisbane",
    "Asia/Qyzylorda": "(GMT+6:00) Almaty, Novosibirsk",
    "Asia/Aqtobe": "(GMT+5:00) Ekaterinburg",
    "America/Eirunepe": "(GMT-5:00) Bogota, Lima, Quito",
    "America/Toronto": "(GMT-4:00) Eastern Time",
    "Pacific/Honolulu": "(GMT-10:00) Hawaii",
    "America/Montevideo": "(GMT-3:00) Montevideo",
    "America/Blanc-Sablon": "(GMT-4:00) Caracas, La Paz",
    "Asia/Tashkent": "(GMT+5:00) Islamabad, Karachi, Tashkent",
    "America/Managua": "(GMT-6:00) Central America",
    "Africa/Niamey": "(GMT+1:00) West Central Africa",
    "Africa/Banjul": "(GMT+0:00) Casablanca, Monrovia",
    "Asia/Phnom_Penh": "(GMT+7:00) Bangkok, Hanoi, Jakarta",
    "America/Creston": "(GMT-7:00) Pacific Time",
    "Pacific/Efate": "(GMT+11:00) Magadan, Solomon Islands, New Caledonia",
    "Europe/Brussels": "(GMT+2:00) Brussels, Copenhagen, Madrid, Paris",
    "America/El_Salvador": "(GMT-6:00) Central America",
    "Africa/Ouagadougou": "(GMT+0:00) Casablanca, Monrovia",
    "Indian/Kerguelen": "(GMT+5:00) Islamabad, Karachi, Tashkent",
    "Atlantic/Canary": "(GMT+1:00) Canary Islands",
    "Asia/Vientiane": "(GMT+7:00) Bangkok, Hanoi, Jakarta",
    "Europe/Bucharest": "(GMT+3:00) Bucharest",
    "Africa/Lusaka": "(GMT+2:00) Harare, Pretoria",
    "Asia/Kathmandu": "(GMT+5:45) Kathmandu",
    "Africa/Harare": "(GMT+2:00) Harare, Pretoria",
    "Asia/Bangkok": "(GMT+7:00) Bangkok, Hanoi, Jakarta",
    "America/Denver": "(GMT-6:00) Saskatchewan",
    "Africa/Lome": "(GMT+0:00) Casablanca, Monrovia",
    "Europe/Kiev": "(GMT+3:00) Bucharest",
    "Europe/Vienna": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
    "Europe/Rome": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
    "Asia/Manila": "(GMT+8:00) Taipei",
    "Asia/Tokyo": "(GMT+9:00) Osaka, Sapporo, Tokyo",
    "Africa/Kigali": "(GMT+2:00) Harare, Pretoria",
    "Europe/Chisinau": "(GMT+3:00) Bucharest",
    "America/Winnipeg": "(GMT-5:00) Central Time",
    "America/Nassau": "(GMT-4:00) Caracas, La Paz",
    "Europe/Dublin": "(GMT+1:00) Dublin",
    "Asia/Kuching": "(GMT+8:00) Kuala Lumpur, Singapore",
    "Asia/Colombo": "(GMT+5:30) Sri Jayawardenepura",
    "Asia/Krasnoyarsk": "(GMT+7:00) Krasnoyarsk",
    "America/St_Johns": "(GMT-2:30) Newfoundland and Labrador",
    "Africa/Luanda": "(GMT-1:00) Cape Verde Islands",
    "America/Guyana": "(GMT-4:00) Caracas, La Paz",
    "Europe/Paris": "(GMT+2:00) Brussels, Copenhagen, Madrid, Paris",
    "Africa/Abidjan": "(GMT+0:00) Casablanca, Monrovia",
    "America/Regina": "(GMT-6:00) Saskatchewan",
    "America/Thule": "(GMT-3:00) Brasilia",
    "America/Campo_Grande": "(GMT-4:00) Caracas, La Paz",
    "Africa/Tunis": "(GMT+1:00) West Central Africa",
    "America/Rankin_Inlet": "(GMT-5:00) Central Time",
    "Europe/Copenhagen": "(GMT-2:00) Greenland",
    "Asia/Dubai": "(GMT+4:00) Abu Dhabi, Muscat",
    "America/Whitehorse": "(GMT-7:00) Pacific Time",
    "America/Santarem": "(GMT-3:00) Brasilia",
    "Africa/Djibouti": "(GMT+3:00) Nairobi",
    "Africa/Casablanca": "(GMT+1:00) Lisbon",
    "Asia/Hebron": "(GMT+3:00) Jerusalem",
    "America/Maceio": "(GMT-3:00) Brasilia",
    "Africa/Khartoum": "(GMT+2:00) Cairo",
    "Africa/Douala": "(GMT+1:00) West Central Africa",
    "Asia/Kuala_Lumpur": "(GMT+8:00) Kuala Lumpur, Singapore",
    "Africa/Kinshasa": "(GMT+1:00) West Central Africa",
    "Europe/Riga": "(GMT+3:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
    "America/Sao_Paulo": "(GMT-3:00) Brasilia",
    "Africa/Tripoli": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
    "Europe/Madrid": "(GMT+2:00) Brussels, Copenhagen, Madrid, Paris",
    "America/Danmarkshavn": "(GMT+0:00) Azores",
    "Europe/Skopje":
        "(GMT+2:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    "America/Porto_Velho": "(GMT-4:00) Caracas, La Paz",
    "Africa/Maseru": "(GMT+2:00) Harare, Pretoria",
    "Europe/Sofia": "(GMT+3:00) Bucharest",
    "Asia/Dili": "(GMT+9:00) Seoul",
    "Asia/Almaty": "(GMT+6:00) Almaty, Novosibirsk",
    "Europe/Sarajevo": "(GMT+2:00) Sarajevo, Skopje, Warsaw, Zagreb",
    "America/Boa_Vista": "(GMT-4:00) Caracas, La Paz",
    "Africa/Addis_Ababa": "(GMT+3:00) Nairobi",
    "Asia/Pontianak": "(GMT+7:00) Bangkok, Hanoi, Jakarta",
    "Africa/Lubumbashi": "(GMT+2:00) Harare, Pretoria",
    "Europe/Helsinki": "(GMT+3:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
    "Africa/Monrovia": "(GMT-10:00) Hawaii",
    "Asia/Muscat": "(GMT+4:00) Abu Dhabi, Muscat",
    "Europe/Oslo": "(GMT-2:00) Greenland",
    "America/Cayenne": "(GMT-3:00) Brasilia",
    "Asia/Kolkata": "(GMT+5:30) Chennai, Kolkata, Mumbai, New Delhi",
    "America/Cuiaba": "(GMT-4:00) Caracas, La Paz",
    "Africa/Maputo": "(GMT+2:00) Harare, Pretoria",
    "Asia/Anadyr": "(GMT+12:00) Kamchatka, Marshall Islands",
    "Asia/Kabul": "(GMT+4:30) Kabul",
    "America/Santa_Isabel": "(GMT-7:00) Dawson, Yukon",
    "Asia/Damascus": "(GMT+3:00) Jerusalem",
    "America/Juneau": "(GMT-8:00) Alaska",
    "Pacific/Noumea": "(GMT+11:00) Magadan, Solomon Islands, New Caledonia",
    "Asia/Kamchatka": "(GMT+12:00) Kamchatka, Marshall Islands",
    "America/Anchorage": "(GMT-8:00) Alaska",
    "America/Matamoros": "(GMT-5:00) Guadalajara, Mexico City, Monterrey",
    "Asia/Omsk": "(GMT+6:00) Almaty, Novosibirsk",
    "Africa/Algiers": "(GMT+1:00) West Central Africa",
    "America/Guayaquil": "(GMT-5:00) Bogota, Lima, Quito",
    "Pacific/Auckland": "(GMT+12:00) Fiji Islands",
    "Europe/Amsterdam":
        "(GMT+2:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    "America/Monterrey": "(GMT-5:00) Guadalajara, Mexico City, Monterrey",
    "Africa/Juba": "(GMT+3:00) Nairobi",
    "Europe/Stockholm": "(GMT-2:00) Greenland",
    "America/Costa_Rica": "(GMT-6:00) Central America",
    "America/Caracas": "(GMT-4:00) Caracas, La Paz",
    "Asia/Hong_Kong": "(GMT+8:00) Taipei",
    "Europe/Uzhgorod": "(GMT+3:00) Bucharest",
    "Asia/Makassar": "(GMT+8:00) Kuala Lumpur, Singapore",
    "Europe/Minsk": "(GMT+3:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
    "America/Havana": "(GMT-4:00) Eastern Time",
    "America/Cancun": "(GMT-5:00) Guadalajara, Mexico City, Monterrey",
    "America/Hermosillo": "(GMT-7:00) Tijuana",
    "America/Belem": "(GMT-3:00) Brasilia",
    "Asia/Chongqing": "(GMT+8:00) Beijing, Chongqing, Hong Kong SAR, Urumqi",
    "Asia/Beirut": "(GMT+3:00) Jerusalem",
    "America/Guatemala": "(GMT-6:00) Central America",
    "Asia/Urumqi": "(GMT+6:00) Almaty, Novosibirsk",
    "America/Mazatlan": "(GMT-6:00) Chihuahua, La Paz, Mazatlan",
    "America/Puerto_Rico": "(GMT-4:00) Caracas, La Paz",
    "America/Bogota": "(GMT-5:00) Bogota, Lima, Quito"
};
export default citiesToTimeZoneMap;
